/** \file diffusion.c
  * \brief Starting at the given IC, successively iterate the IM and SM to gain action.
  *
  * NOTES: 
  *		Fourier-Taylor coeffs for the generating function are read from files
  *		ddA.res and ddB.res, which were generated by FT. 
  *
  *		Taylor coeffs for omega are read from ddOmega.res, which was generated
  *		by T.
  *
  * USAGE:	./diffusion 3 0
  *
  * CALLED BY:	
  *
  */

#include <stdlib.h>
#include <stdio.h>
#include <math.h>       // fabs
#include "FT_module.h"
#include "T_module.h"
#include "SM_module.h"
#include "IM_module.h"


int
main (int argc, char *argv[])
{
	const int nfour=64; 	/* Number of Fourier coeffs used in FFT */
	const int ntori=5;		/* Number of tori used in numerical SM */

	double ddA[nfour][ntori];	/* divided differences of Fourier coeffs A_n(I) */
	double ddB[nfour][ntori];	/* divided differences of Fourier coeffs B_n(I) */
    double ddOmega[ntori];      /* divided differences of omega(I) */

    const int N = 2;    /* Degree of Fourier series */
    const int M = 2;    /* Degree of Taylor series */

    double I, phi;      /* (I, \phi) = Point in the domain of the SM */
    double Ip, phip;    /* (I', \phi') = Image of (I, phi) by the SM */

    const double tol=0.2;       /* Tolerance to be at a min/max of the SM */

    if(argc != 3)
    {
        fprintf(stderr, "Num of args incorrect. Usage: %s scaled_I phi\n",
              argv[0]);
        exit(EXIT_FAILURE);
    }

    I = atof(argv[1]);	    /* scaled action level, e.g. I=2 */
    phi = atof(argv[2]);	/* \phi */

    /* Read FT series (divided differences) from file */
    read_FT(nfour,ntori,ddA,ddB);

    /* Read Taylor series (divided differences) from file */
    read_T(ntori,ddOmega);

	printf("%f %f %s\n", I, phi, "IM");
    while(I<6)
    {
        /* Here, trajactory is at a maximum of the SM */

        while(!(fabs(phi-1.75) < tol || fabs(phi-(M_PI+1.75)) < tol))
        {
            /* Compute the IM: (I, phi) -> (Ip, phip) */
            IM(I, phi, &Ip, &phip);
            I = Ip;
            phi = (phip>M_PI ? phip-M_PI : phip);
            
            printf("%f %f %s\n", I, phi, "IM");
        }
        /* Here, trajactory is at a minimum of the SM */

        //while(!(fabs(phi-0) < tol || fabs(phi-M_PI) < tol))
        //{
            /* Compute the SM: (I, phi) -> (Ip, phip) */
            SM(nfour, ntori, ddA, ddB, ddOmega, N, M, I, phi, &Ip, &phip);
            I = Ip;
            phi = (phip>M_PI ? phip-M_PI : phip);
            
            printf("%f %f %s\n", I, phi, "SM");
        //}
    }
    return 0;
}
