/** \file SM.c
  * \brief Compute the scattering map \f$ (I', \phi') = \sigma(I,\phi) \f$.
  *
  *	The degree (N,M) of the Fourier-Taylor series can be modified in the code.
  *
  * NOTES: 
  *		Fourier-Taylor coeffs for the generating function are read from files
  *		ddA.res and ddB.res, which were generated by FT. 
  *
  *		Taylor coeffs for omega are read from ddOmega.res, which was generated
  *		by T.
  *
  * USAGE:	./SM 2 0
  *
  * CALLED BY:	
  *
  */

#include <stdlib.h>
#include <stdio.h>
#include "FT_module.h"
#include "T_module.h"
#include "SM_module.h"


int
main (int argc, char *argv[])
{
	const int nfour=65; 	/* Number of Fourier coeffs used in FFT */
	const int ntori=8;		/* Number of tori used in numerical SM */

	double ddA[nfour][ntori];	/* divided differences of Fourier coeffs A_n(I) */
	double ddB[nfour][ntori];	/* divided differences of Fourier coeffs B_n(I) */
    double ddOmega[ntori-1];      /* divided differences of omega(I) */

    const int N = 2;    /* Degree of Fourier series */
    const int M = 2;    /* Degree of Taylor series */

    double I, phi;      /* (I, \phi) = Point in the domain of the SM */
    double Ip, phip;    /* (I', \phi') = Image of (I, phi) by the SM */

    if(argc != 3)
    {
        fprintf(stderr, "Num of args incorrect. Usage: %s scaled_I phi\n",
              argv[0]);
        exit(EXIT_FAILURE);
    }

    I = atof(argv[1]);	    /* scaled action level, e.g. I=2 */
    phi = atof(argv[2]);	/* \phi */

    /* Read FT series (divided differences) from file */
    read_FT(nfour,ntori,ddA,ddB);

    /* Read Taylor series (divided differences) from file */
    read_T(ntori-1,ddOmega);

	/* Compute the SM: (I, phi) -> (Ip, phip) */
	SM(nfour, ntori, ddA, ddB, ddOmega, N, M, I, phi, &Ip, &phip);
	
    printf("%f %f\n", Ip, phip);
    return 0;
}
